{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# COVID-19 Image Classification Documentation\n",
    "\n",
    "This Jupyter notebook outlines a Python script that performs image classification on a dataset of COVID-19 images. The dataset used can be found at [this Kaggle link](https://www.kaggle.com/datasets/pranavraikokte/covid19-image-dataset/data).\n",
    "\n",
    "## Table of Contents\n",
    "\n",
    "1. [Importing Libraries](#importing-libraries)\n",
    "2. [Loading and Preprocessing Data](#loading-and-preprocessing-data)\n",
    "3. [Data Splitting](#data-splitting)\n",
    "4. [Data Augmentation](#data-augmentation)\n",
    "5. [Building the Model](#building-the-model)\n",
    "6. [Training the Model](#training-the-model)\n",
    "7. [Visualizing Training Results](#visualizing-training-results)\n",
    "8. [Saving the Model](#saving-the-model)\n",
    "\n",
    "## Importing Libraries\n",
    "\n",
    "The script begins by importing necessary libraries.\n",
    "\n",
    "```python\n",
    "import os\n",
    "import glob\n",
    "import numpy as np\n",
    "import cv2\n",
    "import tensorflow as tf\n",
    "from sklearn.model_selection import train_test_split\n",
    "from tensorflow.keras import layers, models\n",
    "from tensorflow.keras.applications import VGG16\n",
    "import matplotlib.pyplot as plt\n",
    "```\n",
    "\n",
    "## Loading and Preprocessing Data\n",
    "\n",
    "The script loads images from the dataset and preprocesses them. It resizes the images to 224x224 pixels and normalizes the pixel values to be between 0 and 1.\n",
    "\n",
    "```python\n",
    "all_images = []\n",
    "all_labels = []\n",
    "for i, item in enumerate(glob.glob('./covid_19/**')):\n",
    "    all_labels.append(item.split('\\\\')[-2])\n",
    "    img = cv2.imread(item)\n",
    "    img = cv2.resize(img, (224, 224)) / 255\n",
    "    all_images.append(img)\n",
    "\n",
    "all_images = np.array(all_images)\n",
    "```\n",
    "\n",
    "## Data Splitting\n",
    "\n",
    "The dataset is split into training and testing sets using the `train_test_split` function from `sklearn.model_selection`.\n",
    "\n",
    "```python\n",
    "x_train, x_test, y_train, y_test = train_test_split(all_images, all_labels)\n",
    "all_images = []\n",
    "all_labels = []\n",
    "```\n",
    "\n",
    "## Data Augmentation\n",
    "\n",
    "Data augmentation is performed using `tf.keras.preprocessing.image.ImageDataGenerator`. This helps to increase the diversity of the training set and improve the model's ability to generalize.\n",
    "\n",
    "```python\n",
    "aug = tf.keras.preprocessing.image.ImageDataGenerator(rotation_range=10, fill_mode='nearest')\n",
    "```\n",
    "\n",
    "## Building the Model\n",
    "\n",
    "The model is built using the VGG16 architecture as a base model. The top layers of the VGG16 model are removed, and new layers are added on top. The base model's layers are frozen to prevent them from being updated during training.\n",
    "\n",
    "```python\n",
    "base_model = VGG16(weights='imagenet', include_top=False, input_tensor=layers.Input(shape=(224, 224, 3)))\n",
    "\n",
    "for layer in base_model.layers:\n",
    "    layer.trainable = False\n",
    "\n",
    "network = models.Sequential([\n",
    "    base_model,\n",
    "    layers.MaxPool2D((4, 4)),\n",
    "    layers.Flatten(),\n",
    "    layers.Dense(64, activation='relu'),\n",
    "    layers.Dense(2, activation='softmax')\n",
    "])\n",
    "\n",
    "opt = tf.keras.optimizers.Adam(learning_rate=0.01, decay=0.00025)\n",
    "network.compile(optimizer=opt, metrics=['accuracy'], loss='binary_crossentropy')\n",
    "network.summary()\n",
    "```\n",
    "\n",
    "## Training the Model\n",
    "\n",
    "The model is trained using the training data and validated using the testing data.\n",
    "\n",
    "```python\n",
    "H = network.fit(\n",
    "    aug.flow(x_train, y_train, batch_size=8),\n",
    "    steps_per_epoch=len(x_train) // 8,\n",
    "    validation_data=(x_test, y_test),\n",
    "    epochs=5\n",
    ")\n",
    "```\n",
    "\n",
    "## Visualizing Training Results\n",
    "\n",
    "The training and validation accuracy and loss are plotted using `matplotlib.pyplot`.\n",
    "\n",
    "```python\n",
    "plt.style.use('ggplot')\n",
    "plt.plot(H.history['accuracy'], label='train_accuracy')\n",
    "plt.plot(H.history['val_accuracy'], label='val_accuracy')\n",
    "plt.plot(H.history['loss'], label='train_loss')\n",
    "plt.plot(H.history['val_loss'], label='val_accuracy')\n",
    "plt.xlabel('epochs')\n",
    "plt.ylabel('sss')\n",
    "plt.title('classification')\n",
    "plt.show()\n",
    "```\n",
    "\n",
    "## Saving the Model\n",
    "\n",
    "Finally, the trained model is saved to a file named 'covide.h5'.\n",
    "\n",
    "```python\n",
    "network.save('covide.h5')\n",
    "```"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os \n",
    "import glob \n",
    "import numpy as np\n",
    "import cv2\n",
    "all_images = []\n",
    "all_labels = []\n",
    "for i,item in enumerate(glob.glob('.\\covid_19\\*\\*')):\n",
    "    all_labels.append(item.split('\\\\')[-2])\n",
    "    img=cv2.imread(item)\n",
    "    img=cv2.resize(img,(224,224))/255\n",
    "    all_images.append(img)  \n",
    "\n",
    "\n",
    "all_images=np.array(all_images)  \n",
    "  \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.model_selection import train_test_split\n",
    "x_train,x_test,y_train,y_test = train_test_split(all_images,all_labels)\n",
    "all_images=[]\n",
    "all_labels=[]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import tensorflow as tf\n",
    "aug=tf.keras.preprocessing.image.ImageDataGenerator(\n",
    "    rotation_range=10, fill_mode='nearest')\n",
    "\n",
    "from tensorflow.keras import layers ,  models\n",
    "from tensorflow.keras.applications import VGG16\n",
    "\n",
    "base_model=VGG16(weights='imagenet',include_top=False,\n",
    "input_tensor=layers.Input(shape=(224,224,3)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model: \"sequential\"\n",
      "_________________________________________________________________\n",
      " Layer (type)                Output Shape              Param #   \n",
      "=================================================================\n",
      " vgg16 (Functional)          (None, 7, 7, 512)         14714688  \n",
      "                                                                 \n",
      " max_pooling2d (MaxPooling2D  (None, 1, 1, 512)        0         \n",
      " )                                                               \n",
      "                                                                 \n",
      " flatten (Flatten)           (None, 512)               0         \n",
      "                                                                 \n",
      " dense (Dense)               (None, 64)                32832     \n",
      "                                                                 \n",
      " dense_1 (Dense)             (None, 2)                 130       \n",
      "                                                                 \n",
      "=================================================================\n",
      "Total params: 14,747,650\n",
      "Trainable params: 32,962\n",
      "Non-trainable params: 14,714,688\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "for layer in base_model.layers:\n",
    "    layer.trainable=False\n",
    "\n",
    "network=models.Sequential([\n",
    "\n",
    "    base_model,\n",
    "    layers.MaxPool2D((4,4)),\n",
    "    layers.Flatten(),\n",
    "    layers.Dense(64,activation='relu'),\n",
    "    layers.Dense(2,activation='softmax')\n",
    "\n",
    "])\n",
    "\n",
    "opt=tf.keras.optimizers.Adam(learning_rate=0.01,decay=0.00025)\n",
    "network.compile(optimizer=opt,metrics=['accuracy'],loss='binary_crossentropy')\n",
    "network.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/5\n",
      "1294/1294 [==============================] - ETA: 0s - loss: 0.3526 - accuracy: 0.8474"
     ]
    },
    {
     "ename": "ResourceExhaustedError",
     "evalue": "Graph execution error:\n\nDetected at node 'sequential/vgg16/block1_conv2/Conv2D' defined at (most recent call last):\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\runpy.py\", line 192, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\runpy.py\", line 85, in _run_code\n      exec(code, run_globals)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n      app.launch_new_instance()\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n      app.start()\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 677, in start\n      self.io_loop.start()\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\asyncio\\base_events.py\", line 563, in run_forever\n      self._run_once()\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\asyncio\\base_events.py\", line 1844, in _run_once\n      handle._run()\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\asyncio\\events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 473, in dispatch_queue\n      await self.process_one()\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 462, in process_one\n      await dispatch(*args)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 369, in dispatch_shell\n      await result\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 664, in execute_request\n      reply_content = await reply_content\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 355, in do_execute\n      res = shell.run_cell(code, store_history=store_history, silent=silent)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 532, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2854, in run_cell\n      result = self._run_cell(\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2900, in _run_cell\n      return runner(coro)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3098, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3301, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3361, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"C:\\Users\\roozbehbadiee\\AppData\\Local\\Temp\\ipykernel_15616\\1255651741.py\", line 1, in <cell line: 1>\n      H=network.fit(\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1420, in fit\n      val_logs = self.evaluate(\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1716, in evaluate\n      tmp_logs = self.test_function(iterator)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1525, in test_function\n      return step_function(self, iterator)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1514, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1507, in run_step\n      outputs = model.test_step(data)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1471, in test_step\n      y_pred = self(x, training=False)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\sequential.py\", line 374, in call\n      return super(Sequential, self).call(inputs, training=training, mask=mask)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\layers\\convolutional.py\", line 248, in call\n      outputs = self.convolution_op(inputs, self.kernel)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\layers\\convolutional.py\", line 233, in convolution_op\n      return tf.nn.convolution(\nNode: 'sequential/vgg16/block1_conv2/Conv2D'\nOOM when allocating tensor with shape[32,64,224,224] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n\t [[{{node sequential/vgg16/block1_conv2/Conv2D}}]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\n [Op:__inference_test_function_6923]",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mResourceExhaustedError\u001b[0m                    Traceback (most recent call last)",
      "\u001b[1;32mc:\\Users\\roozbehbadiee\\Desktop\\deeplearning roboteach\\sec 5\\cov_tf_learning.ipynb Cell 6'\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[1;34m()\u001b[0m\n\u001b[1;32m----> <a href='vscode-notebook-cell:/c%3A/Users/roozbehbadiee/Desktop/deeplearning%20roboteach/sec%205/cov_tf_learning.ipynb#ch0000005?line=0'>1</a>\u001b[0m H\u001b[39m=\u001b[39mnetwork\u001b[39m.\u001b[39;49mfit(\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/roozbehbadiee/Desktop/deeplearning%20roboteach/sec%205/cov_tf_learning.ipynb#ch0000005?line=1'>2</a>\u001b[0m     aug\u001b[39m.\u001b[39;49mflow(x_train,y_train,batch_size\u001b[39m=\u001b[39;49m \u001b[39m8\u001b[39;49m),\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/roozbehbadiee/Desktop/deeplearning%20roboteach/sec%205/cov_tf_learning.ipynb#ch0000005?line=2'>3</a>\u001b[0m     steps_per_epoch\u001b[39m=\u001b[39;49m\u001b[39mlen\u001b[39;49m(x_train)\u001b[39m/\u001b[39;49m\u001b[39m/\u001b[39;49m\u001b[39m8\u001b[39;49m,\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/roozbehbadiee/Desktop/deeplearning%20roboteach/sec%205/cov_tf_learning.ipynb#ch0000005?line=3'>4</a>\u001b[0m     validation_data\u001b[39m=\u001b[39;49m(x_test,y_test),epochs\u001b[39m=\u001b[39;49m\u001b[39m5\u001b[39;49m\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/roozbehbadiee/Desktop/deeplearning%20roboteach/sec%205/cov_tf_learning.ipynb#ch0000005?line=4'>5</a>\u001b[0m )\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\utils\\traceback_utils.py:67\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     <a href='file:///c%3A/Users/roozbehbadiee/anaconda3/envs/tf2_8gpu_env/lib/site-packages/keras/utils/traceback_utils.py?line=64'>65</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m e:  \u001b[39m# pylint: disable=broad-except\u001b[39;00m\n\u001b[0;32m     <a href='file:///c%3A/Users/roozbehbadiee/anaconda3/envs/tf2_8gpu_env/lib/site-packages/keras/utils/traceback_utils.py?line=65'>66</a>\u001b[0m   filtered_tb \u001b[39m=\u001b[39m _process_traceback_frames(e\u001b[39m.\u001b[39m__traceback__)\n\u001b[1;32m---> <a href='file:///c%3A/Users/roozbehbadiee/anaconda3/envs/tf2_8gpu_env/lib/site-packages/keras/utils/traceback_utils.py?line=66'>67</a>\u001b[0m   \u001b[39mraise\u001b[39;00m e\u001b[39m.\u001b[39mwith_traceback(filtered_tb) \u001b[39mfrom\u001b[39;00m \u001b[39mNone\u001b[39m\n\u001b[0;32m     <a href='file:///c%3A/Users/roozbehbadiee/anaconda3/envs/tf2_8gpu_env/lib/site-packages/keras/utils/traceback_utils.py?line=67'>68</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m     <a href='file:///c%3A/Users/roozbehbadiee/anaconda3/envs/tf2_8gpu_env/lib/site-packages/keras/utils/traceback_utils.py?line=68'>69</a>\u001b[0m   \u001b[39mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\tensorflow\\python\\eager\\execute.py:54\u001b[0m, in \u001b[0;36mquick_execute\u001b[1;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[0;32m     <a href='file:///c%3A/Users/roozbehbadiee/anaconda3/envs/tf2_8gpu_env/lib/site-packages/tensorflow/python/eager/execute.py?line=51'>52</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m     <a href='file:///c%3A/Users/roozbehbadiee/anaconda3/envs/tf2_8gpu_env/lib/site-packages/tensorflow/python/eager/execute.py?line=52'>53</a>\u001b[0m   ctx\u001b[39m.\u001b[39mensure_initialized()\n\u001b[1;32m---> <a href='file:///c%3A/Users/roozbehbadiee/anaconda3/envs/tf2_8gpu_env/lib/site-packages/tensorflow/python/eager/execute.py?line=53'>54</a>\u001b[0m   tensors \u001b[39m=\u001b[39m pywrap_tfe\u001b[39m.\u001b[39mTFE_Py_Execute(ctx\u001b[39m.\u001b[39m_handle, device_name, op_name,\n\u001b[0;32m     <a href='file:///c%3A/Users/roozbehbadiee/anaconda3/envs/tf2_8gpu_env/lib/site-packages/tensorflow/python/eager/execute.py?line=54'>55</a>\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[0;32m     <a href='file:///c%3A/Users/roozbehbadiee/anaconda3/envs/tf2_8gpu_env/lib/site-packages/tensorflow/python/eager/execute.py?line=55'>56</a>\u001b[0m \u001b[39mexcept\u001b[39;00m core\u001b[39m.\u001b[39m_NotOkStatusException \u001b[39mas\u001b[39;00m e:\n\u001b[0;32m     <a href='file:///c%3A/Users/roozbehbadiee/anaconda3/envs/tf2_8gpu_env/lib/site-packages/tensorflow/python/eager/execute.py?line=56'>57</a>\u001b[0m   \u001b[39mif\u001b[39;00m name \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n",
      "\u001b[1;31mResourceExhaustedError\u001b[0m: Graph execution error:\n\nDetected at node 'sequential/vgg16/block1_conv2/Conv2D' defined at (most recent call last):\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\runpy.py\", line 192, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\runpy.py\", line 85, in _run_code\n      exec(code, run_globals)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n      app.launch_new_instance()\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n      app.start()\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 677, in start\n      self.io_loop.start()\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\asyncio\\base_events.py\", line 563, in run_forever\n      self._run_once()\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\asyncio\\base_events.py\", line 1844, in _run_once\n      handle._run()\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\asyncio\\events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 473, in dispatch_queue\n      await self.process_one()\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 462, in process_one\n      await dispatch(*args)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 369, in dispatch_shell\n      await result\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 664, in execute_request\n      reply_content = await reply_content\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 355, in do_execute\n      res = shell.run_cell(code, store_history=store_history, silent=silent)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 532, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2854, in run_cell\n      result = self._run_cell(\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2900, in _run_cell\n      return runner(coro)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3098, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3301, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3361, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"C:\\Users\\roozbehbadiee\\AppData\\Local\\Temp\\ipykernel_15616\\1255651741.py\", line 1, in <cell line: 1>\n      H=network.fit(\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1420, in fit\n      val_logs = self.evaluate(\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1716, in evaluate\n      tmp_logs = self.test_function(iterator)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1525, in test_function\n      return step_function(self, iterator)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1514, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1507, in run_step\n      outputs = model.test_step(data)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1471, in test_step\n      y_pred = self(x, training=False)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\sequential.py\", line 374, in call\n      return super(Sequential, self).call(inputs, training=training, mask=mask)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\layers\\convolutional.py\", line 248, in call\n      outputs = self.convolution_op(inputs, self.kernel)\n    File \"C:\\Users\\roozbehbadiee\\anaconda3\\envs\\tf2_8gpu_env\\lib\\site-packages\\keras\\layers\\convolutional.py\", line 233, in convolution_op\n      return tf.nn.convolution(\nNode: 'sequential/vgg16/block1_conv2/Conv2D'\nOOM when allocating tensor with shape[32,64,224,224] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n\t [[{{node sequential/vgg16/block1_conv2/Conv2D}}]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\n [Op:__inference_test_function_6923]"
     ]
    }
   ],
   "source": [
    "H=network.fit(\n",
    "    aug.flow(x_train,y_train,batch_size= 8),\n",
    "    steps_per_epoch=len(x_train)//8,\n",
    "    validation_data=(x_test,y_test),epochs=5\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt \n",
    "plt.style.use('ggplot')\n",
    "plt.plot(H.history['accuracy'],label='train_accuracy')\n",
    "plt.plot(H.history['val_accuracy'],label='val_accuracy')\n",
    "plt.plot(H.history['loss'],label='train_loss')\n",
    "plt.plot(H.history['val_loss'],label='val_accuracy')\n",
    "plt.xlabel('epochs')\n",
    "plt.ylabel('sss')\n",
    "plt.title('classfication')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "network.save('covide.h5')"
   ]
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "7b4b38f84c893d4679228e7d3ce472830242e3f4b95a448debba7d0e68d7549a"
  },
  "kernelspec": {
   "display_name": "Python 3.8.8 ('base')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
